config/routes.rb
Rails.application.routes.draw do
  resources :item_types, only: [:index, :show] do
    resources :items
  end  

  root "item_types#index"

end

app/models/item.rb
class Item < ActiveRecord::Base
    belongs_to :item_type
 
    validates :title, presence: true, length: { minimum: 2}

  def completed?
    !completed_on.nil?
  end

  def item_type_name
    if item_type
      item_type.name
    else
      'No item type'
    end  
  end

  def get_image
    logger.debug "Get an Image!"
    update_attribute(:image_url, ImageFetcher.new.fetch(title))
  end
end

app/models/item_type.rb
class ItemType < ActiveRecord::Base
  has_many :items, dependent: :nullify
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/item_type_controller.rb
class ItemTypeController < ApplicationController
  def index
    @item_types = ItemType.all
  end

  def show
    @item_type = ItemType.find(params[:id])
  end

end

app/controllers/item_types_controller.rb
class ItemTypesController < ApplicationController
    def index
    @item_types = ItemType.all
  end

  def show
    @item_type = ItemType.find(params[:id])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :lookup_item_type
  before_action :lookup_item, only: [:show, :edit, :update, :destroy]

   def index
    @items = @item_type.items.order('title ASC') #title sorted 'Ascending'
   end

   def show
     @items = @item_type.items.find(params[:id])
   end


   def new
     @item = @item_type.items.new
   end

   def create
    @item = @item_type.items.new(item_params)
      if @item.save
         @item.get_image
         redirect_to root_path, notice: "Sucess! We added your Item!"
      else
        render 'new'
      end
   end

   def edit
     @item = @item_type.items.find(params[:id])
   end

   def update
    @item = update_attributes(params[:id])
    @item.get_image if @item.image_url.nil?
      if @item.update_attributes(item_params)
        redirect_to root_path, notice: "Sucess!  We saved #{@item.title}!!"
      else
        render 'new'
      end
   end

   def destroy
    @item = destroy
    @item.destroy
    redirect_to root_path, notice: ":(  It's gone!"
   end

  private
    # this is run before every action is started
    def lookup_item_type
      @item_type = ItemType.find(params[:item_type_id])
    end

    def lookup_item
      @item = @item_type.items.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:title, :body, :completed_on)
    end

 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_type_helper.rb
module ItemTypeHelper
end

app/helpers/item_types_helper.rb
module ItemTypesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/item_type/index.html.erb
<h1>Select an Item Type</h1>

<% @item_types.each do |item_type| %>
  <h3><%= item_type.name %></h3>

  <p><%= link_to 'Add a new one', new_item_type_item_path(item_type) %></p>

  <% item_type.items.each do |item| %>
    <p><%= link_to item.title, item_type_item_path(item_type, item) %></p>
  <% end %>
<% end %>

<!--
<div class="row">
   <div class="col-xs-12">
    <h1>Items in the Library</h1>

    <p>We have <%= @items.count %> Items!</p>
    <p><%= link_to 'New Item', new_item_type_item_path(@item_type) %></p>
   </div>
  </div>
  <div>
   <hr />  
    <%= render 'layouts/item' %>
  </div>     -->

app/views/item_types/_item_type.html.erb
<p><%= link_to 'Add a new one', new_item_type_item_path(item_type) %></p>

  <% item_type.items.each do |item| %>
    <%= render item %>
    <p><%= link_to item.title, item_type_item_path(item_type, item) %></p>
  <% end %>

app/views/item_types/index.html.erb
<div class="row">
   <div class="col-xs-12">
    <h1>Items in the Library</h1>

<% @item_types.each do |item_type| %>
  <h3><%= item_type.name %></h3>

  <%= render item_type %>
  
<% end %>
  </div>
  </div>
  <div>
   <hr />  
    <%#= render 'layouts/item' %>
  </div>     

app/views/items/_form.html.erb
  <% if @item.errors.any? %>

    <div class='errors'>
      <h2>Uh oh, errors!</h2>
        <% @item.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
        <% end %>
    </div>
  <% end %>

<%= form_for ([@item_type, @item]) do |f| %>

  <div class='field'>
    <!--<%= f.label :item_type, class: 'lable' %>        <!-- Don't need this, as we have driven  
    <!--<%= f.label :item_type, 'What type of item is this?' %>  it to a specific item type. --> 
    <!--<%= f.collection_select :item_type_id, ItemType.all, :id, :name %> -->
    <p>This is going to be a <%= @item_type.name %></p>
  </div>

  <div class='field'>
    <%= f.label :title, class: 'lable' %>
    <%= f.text_field :title %>
  </div>

  <div class='field'>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class='field'>
    <%= f.label :completed_on, 'Completed On: ' %>
    <%= f.date_select :completed_on, include_blank: true %>
  </div>


  <div class='field'>
    <%= f.submit 'Save' %>
  </div>

<% end %>

app/views/items/_item.html.erb
    <div class="row">
    <div id="leftCol" class="col-xs-9">
      <h3><%= item.item_type_name %>: <%= item.title %></h3>
      <% if item.completed? %>
        <p>This item has been completed.</p>
      <% else %>
       <p>Still need to read/watch this.</p>
      <% end %>
    </div>

    <div id="rightcol" class="col-xs-3">
      <p><%= image_tag(item.image_url, alt: "", class: 'thumb')  %></p> 
    </div>
  </div>  

  <div class="row">
   <div class="col-xs-12">
  
    <p>
    <%= link_to 'Edit', edit_item_type_item_path(item.item_type, item) %>
    *
    <%= link_to 'Delete', item_type_item_path(item.item_type, item), method: :delete %>
    </p>

    <p>Click here for more about: <%= link_to(item.title, item_type_item_path(item.item_type, item)) %>
    </p>
    <hr />
   </div> 
  </div>
 

app/views/items/edit.html.erb
<h2>Edit: <%= @item.title %></h2>

<%= render 'form' %>

app/views/items/index.html.erb
  <div class="row">
   <div class="col-xs-12">
    <h1>Items in the Library</h1>

    <p>We have <%= @items.count %> Items!</p>
    <p><%= link_to 'New Item', new_item_type_item_path(@item_type) %></p>
   </div>
  </div>
  <div>
   <hr />  
    <%= render 'layouts/item' %>
  </div>     

app/views/items/new.html.erb
<h1>Add a New Item</h1>

<%= render 'form' %>

app/views/items/show.html.erb
<h1><%= @items.title %></h1>
<hr />
  <div class="row">
    <div id="leftCol" class="col-xs-9">
      This is a
      <%= @items.item_type.name %>
      </p>

      <p>
      <%= @items.body %>
      </p>
    </div>
    <div id="rightcol" class="col-xs-3">
      <p><%= image_tag(@items.image_url, alt: "", :class => 'bigPic')  %></p> 
    </div>
  </div>  
  <div class="row">
   <div class="col-xs-12">
     <p>Completed on: <%= (@items.completed_on) %>.</p>

     <p>
     <%= link_to 'Edit', edit_item_type_item_path %>
     *
     <%= link_to 'Delete', item_type_item_path, method: :delete %>
     </p>
   </div>
  </div> 
<hr />


app/views/layouts/_bootstrapForm.html.erb
=begin
<%= simple_form_for @user_basic, url: create_basic_examples_url, as: 'user_basic' do |f| %>
<%= f.error_notification %>
<%= f.input :email, placeholder: 'Enter email' %>
<%= f.input :password, placeholder: 'Password' %>
<%= f.input :file, as: :file %>
<%= f.input :active %>
<%= f.input :choices, as: :check_boxes,
collection: ["Option one is this and that—be sure to include why it's great", "Option two can be something else and selecting it will deselect option one"] %>
<%= f.input :sex, as: :radio_buttons,
collection: ["Male", "Female"] %>
<%= f.button :submit %>
<% end %>

<%= bootstrap_form_for @item do |f| %>
  <%= f.label :item_type, 'What type of item is this?' %>
  <%= f.collection_select :item_type_id, ItemType.all, :id, :name %><br>
  <%= f.label :title, 'Title'  %>
  <%= f.text_field :title %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.label :completed_on, 'Completed On' %>
  <%= f.date_select :completed_on %>
  <%= f.submit 'Save' %>
<% end %>
=end

app/views/layouts/_footer.html.erb
<div>
<footer class="footer">
  <p><%= link_to 'Home', root_path %></p>
  <hr />
  <small>
    <p>Format and Boostrap stuff from<br/>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a><br />
    
    Overall Project by <a href="http://mowen.imgd.ca/nextweb/">Mike Owen</a>
    </p>
  </small>
</footer>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <!-- <%= link_to "sample app", '#', id: "logo" %> -->
    <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'IMG 240', 'http://adunae.imgd.ca/' %></li>
          <li><%= link_to 'NicGuy59',   'http://mowen.imgd.ca/nextweb/' %></li>          
        </ul>
    </nav>
  </div>
</header>

app/views/layouts/_item.html.erb
  <% @item_types.each do |item| %>
  <div class="row">
    <div id="leftCol" class="col-xs-9">
      <h3><%= item_type_item_name %>: <%= item.title %></h3>
      <% if item.completed? %>
        <p>This item has been completed.</p>
      <% else %>
       <p>Still need to read/watch this.</p>
      <% end %>
    </div>

    <div id="rightcol" class="col-xs-3">
      <p><%= image_tag(item.image_url, alt: "", class: 'thumb')  %></p> 
    </div>
  </div>  

  <div class="row">
   <div class="col-xs-12">
  
    <p>
    <%= link_to 'Edit', edit_item_path(item) %>
    *
    <%= link_to 'Delete', item_path(item), method: :delete %>
    </p>

    <p>Click here for more about: <%= link_to(item.title, item_path(item)) %>
    </p>
    <hr />
   </div> 
  </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- Structure source: "https://www.railstutorial.org/book/filling_in_the_layout" -->
<%= render 'layouts/header' %>
<div class="container">
    <%= yield %>
<%= render 'layouts/footer' %>
</div>  
</body>
</html>